// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/tools/:toolId": {
    params: {
      "toolId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/tools/:toolId" | "/*";
  };
  "./route-modules/home.tsx": {
    id: "route-modules/home";
    page: "/";
  };
  "./route-modules/tool.tsx": {
    id: "route-modules/tool";
    page: "/tools/:toolId";
  };
  "./route-modules/catch-all.tsx": {
    id: "route-modules/catch-all";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "route-modules/home": typeof import("./src/./route-modules/home.tsx");
  "route-modules/tool": typeof import("./src/./route-modules/tool.tsx");
  "route-modules/catch-all": typeof import("./src/./route-modules/catch-all.tsx");
};